//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_1.LanderServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuariosAplic", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UsuariosAplic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioJDEField;
        
        private float CodigoJDEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        private bool EstadoField;
        
        private bool EsPrimeraClaveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string param {
            get {
                return this.paramField;
            }
            set {
                if ((object.ReferenceEquals(this.paramField, value) != true)) {
                    this.paramField = value;
                    this.RaisePropertyChanged("param");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UsuarioJDE {
            get {
                return this.UsuarioJDEField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioJDEField, value) != true)) {
                    this.UsuarioJDEField = value;
                    this.RaisePropertyChanged("UsuarioJDE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float CodigoJDE {
            get {
                return this.CodigoJDEField;
            }
            set {
                if ((this.CodigoJDEField.Equals(value) != true)) {
                    this.CodigoJDEField = value;
                    this.RaisePropertyChanged("CodigoJDE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool EsPrimeraClave {
            get {
                return this.EsPrimeraClaveField;
            }
            set {
                if ((this.EsPrimeraClaveField.Equals(value) != true)) {
                    this.EsPrimeraClaveField = value;
                    this.RaisePropertyChanged("EsPrimeraClave");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Office365", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Office365 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userOffice365Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passOffice365Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serverMailField;
        
        private short portMailField;
        
        private bool enableSslMailField;
        
        private bool autentIntegradaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userOffice365 {
            get {
                return this.userOffice365Field;
            }
            set {
                if ((object.ReferenceEquals(this.userOffice365Field, value) != true)) {
                    this.userOffice365Field = value;
                    this.RaisePropertyChanged("userOffice365");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passOffice365 {
            get {
                return this.passOffice365Field;
            }
            set {
                if ((object.ReferenceEquals(this.passOffice365Field, value) != true)) {
                    this.passOffice365Field = value;
                    this.RaisePropertyChanged("passOffice365");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string serverMail {
            get {
                return this.serverMailField;
            }
            set {
                if ((object.ReferenceEquals(this.serverMailField, value) != true)) {
                    this.serverMailField = value;
                    this.RaisePropertyChanged("serverMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public short portMail {
            get {
                return this.portMailField;
            }
            set {
                if ((this.portMailField.Equals(value) != true)) {
                    this.portMailField = value;
                    this.RaisePropertyChanged("portMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool enableSslMail {
            get {
                return this.enableSslMailField;
            }
            set {
                if ((this.enableSslMailField.Equals(value) != true)) {
                    this.enableSslMailField = value;
                    this.RaisePropertyChanged("enableSslMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool autentIntegrada {
            get {
                return this.autentIntegradaField;
            }
            set {
                if ((this.autentIntegradaField.Equals(value) != true)) {
                    this.autentIntegradaField = value;
                    this.RaisePropertyChanged("autentIntegrada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LanderServices.User_WebServiceSoap")]
    public interface User_WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name pass from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncriptarContraseña", ReplyAction="*")]
        Prueba_1.LanderServices.EncriptarContraseñaResponse EncriptarContraseña(Prueba_1.LanderServices.EncriptarContraseñaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncriptarContraseña", ReplyAction="*")]
        System.Threading.Tasks.Task<Prueba_1.LanderServices.EncriptarContraseñaResponse> EncriptarContraseñaAsync(Prueba_1.LanderServices.EncriptarContraseñaRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarUsuario", ReplyAction="*")]
        Prueba_1.LanderServices.ConsultarUsuarioResponse ConsultarUsuario(Prueba_1.LanderServices.ConsultarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Prueba_1.LanderServices.ConsultarUsuarioResponse> ConsultarUsuarioAsync(Prueba_1.LanderServices.ConsultarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name ParametrosOffice365Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ParametrosOffice365", ReplyAction="*")]
        Prueba_1.LanderServices.ParametrosOffice365Response ParametrosOffice365(Prueba_1.LanderServices.ParametrosOffice365Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ParametrosOffice365", ReplyAction="*")]
        System.Threading.Tasks.Task<Prueba_1.LanderServices.ParametrosOffice365Response> ParametrosOffice365Async(Prueba_1.LanderServices.ParametrosOffice365Request request);
        
        // CODEGEN: Generating message contract since element name User_Cliente_WebService from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuarios", ReplyAction="*")]
        Prueba_1.LanderServices.ListarUsuariosResponse ListarUsuarios(Prueba_1.LanderServices.ListarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<Prueba_1.LanderServices.ListarUsuariosResponse> ListarUsuariosAsync(Prueba_1.LanderServices.ListarUsuariosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncriptarContraseñaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncriptarContraseña", Namespace="http://tempuri.org/", Order=0)]
        public Prueba_1.LanderServices.EncriptarContraseñaRequestBody Body;
        
        public EncriptarContraseñaRequest() {
        }
        
        public EncriptarContraseñaRequest(Prueba_1.LanderServices.EncriptarContraseñaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncriptarContraseñaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pass;
        
        public EncriptarContraseñaRequestBody() {
        }
        
        public EncriptarContraseñaRequestBody(string pass) {
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncriptarContraseñaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncriptarContraseñaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prueba_1.LanderServices.EncriptarContraseñaResponseBody Body;
        
        public EncriptarContraseñaResponse() {
        }
        
        public EncriptarContraseñaResponse(Prueba_1.LanderServices.EncriptarContraseñaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncriptarContraseñaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncriptarContraseñaResult;
        
        public EncriptarContraseñaResponseBody() {
        }
        
        public EncriptarContraseñaResponseBody(string EncriptarContraseñaResult) {
            this.EncriptarContraseñaResult = EncriptarContraseñaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public Prueba_1.LanderServices.ConsultarUsuarioRequestBody Body;
        
        public ConsultarUsuarioRequest() {
        }
        
        public ConsultarUsuarioRequest(Prueba_1.LanderServices.ConsultarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        public ConsultarUsuarioRequestBody() {
        }
        
        public ConsultarUsuarioRequestBody(string user, string Pass) {
            this.user = user;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prueba_1.LanderServices.ConsultarUsuarioResponseBody Body;
        
        public ConsultarUsuarioResponse() {
        }
        
        public ConsultarUsuarioResponse(Prueba_1.LanderServices.ConsultarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Prueba_1.LanderServices.UsuariosAplic ConsultarUsuarioResult;
        
        public ConsultarUsuarioResponseBody() {
        }
        
        public ConsultarUsuarioResponseBody(Prueba_1.LanderServices.UsuariosAplic ConsultarUsuarioResult) {
            this.ConsultarUsuarioResult = ConsultarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParametrosOffice365Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParametrosOffice365", Namespace="http://tempuri.org/", Order=0)]
        public Prueba_1.LanderServices.ParametrosOffice365RequestBody Body;
        
        public ParametrosOffice365Request() {
        }
        
        public ParametrosOffice365Request(Prueba_1.LanderServices.ParametrosOffice365RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ParametrosOffice365RequestBody {
        
        public ParametrosOffice365RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParametrosOffice365Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParametrosOffice365Response", Namespace="http://tempuri.org/", Order=0)]
        public Prueba_1.LanderServices.ParametrosOffice365ResponseBody Body;
        
        public ParametrosOffice365Response() {
        }
        
        public ParametrosOffice365Response(Prueba_1.LanderServices.ParametrosOffice365ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParametrosOffice365ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Prueba_1.LanderServices.Office365 ParametrosOffice365Result;
        
        public ParametrosOffice365ResponseBody() {
        }
        
        public ParametrosOffice365ResponseBody(Prueba_1.LanderServices.Office365 ParametrosOffice365Result) {
            this.ParametrosOffice365Result = ParametrosOffice365Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public Prueba_1.LanderServices.ListarUsuariosRequestBody Body;
        
        public ListarUsuariosRequest() {
        }
        
        public ListarUsuariosRequest(Prueba_1.LanderServices.ListarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string User_Cliente_WebService;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Key_Cliente_WebService;
        
        public ListarUsuariosRequestBody() {
        }
        
        public ListarUsuariosRequestBody(string User_Cliente_WebService, string Key_Cliente_WebService) {
            this.User_Cliente_WebService = User_Cliente_WebService;
            this.Key_Cliente_WebService = Key_Cliente_WebService;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prueba_1.LanderServices.ListarUsuariosResponseBody Body;
        
        public ListarUsuariosResponse() {
        }
        
        public ListarUsuariosResponse(Prueba_1.LanderServices.ListarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Prueba_1.LanderServices.UsuariosAplic[] ListarUsuariosResult;
        
        public ListarUsuariosResponseBody() {
        }
        
        public ListarUsuariosResponseBody(Prueba_1.LanderServices.UsuariosAplic[] ListarUsuariosResult) {
            this.ListarUsuariosResult = ListarUsuariosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface User_WebServiceSoapChannel : Prueba_1.LanderServices.User_WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class User_WebServiceSoapClient : System.ServiceModel.ClientBase<Prueba_1.LanderServices.User_WebServiceSoap>, Prueba_1.LanderServices.User_WebServiceSoap {
        
        public User_WebServiceSoapClient() {
        }
        
        public User_WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public User_WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public User_WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public User_WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prueba_1.LanderServices.EncriptarContraseñaResponse Prueba_1.LanderServices.User_WebServiceSoap.EncriptarContraseña(Prueba_1.LanderServices.EncriptarContraseñaRequest request) {
            return base.Channel.EncriptarContraseña(request);
        }
        
        public string EncriptarContraseña(string pass) {
            Prueba_1.LanderServices.EncriptarContraseñaRequest inValue = new Prueba_1.LanderServices.EncriptarContraseñaRequest();
            inValue.Body = new Prueba_1.LanderServices.EncriptarContraseñaRequestBody();
            inValue.Body.pass = pass;
            Prueba_1.LanderServices.EncriptarContraseñaResponse retVal = ((Prueba_1.LanderServices.User_WebServiceSoap)(this)).EncriptarContraseña(inValue);
            return retVal.Body.EncriptarContraseñaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prueba_1.LanderServices.EncriptarContraseñaResponse> Prueba_1.LanderServices.User_WebServiceSoap.EncriptarContraseñaAsync(Prueba_1.LanderServices.EncriptarContraseñaRequest request) {
            return base.Channel.EncriptarContraseñaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prueba_1.LanderServices.EncriptarContraseñaResponse> EncriptarContraseñaAsync(string pass) {
            Prueba_1.LanderServices.EncriptarContraseñaRequest inValue = new Prueba_1.LanderServices.EncriptarContraseñaRequest();
            inValue.Body = new Prueba_1.LanderServices.EncriptarContraseñaRequestBody();
            inValue.Body.pass = pass;
            return ((Prueba_1.LanderServices.User_WebServiceSoap)(this)).EncriptarContraseñaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prueba_1.LanderServices.ConsultarUsuarioResponse Prueba_1.LanderServices.User_WebServiceSoap.ConsultarUsuario(Prueba_1.LanderServices.ConsultarUsuarioRequest request) {
            return base.Channel.ConsultarUsuario(request);
        }
        
        public Prueba_1.LanderServices.UsuariosAplic ConsultarUsuario(string user, string Pass) {
            Prueba_1.LanderServices.ConsultarUsuarioRequest inValue = new Prueba_1.LanderServices.ConsultarUsuarioRequest();
            inValue.Body = new Prueba_1.LanderServices.ConsultarUsuarioRequestBody();
            inValue.Body.user = user;
            inValue.Body.Pass = Pass;
            Prueba_1.LanderServices.ConsultarUsuarioResponse retVal = ((Prueba_1.LanderServices.User_WebServiceSoap)(this)).ConsultarUsuario(inValue);
            return retVal.Body.ConsultarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prueba_1.LanderServices.ConsultarUsuarioResponse> Prueba_1.LanderServices.User_WebServiceSoap.ConsultarUsuarioAsync(Prueba_1.LanderServices.ConsultarUsuarioRequest request) {
            return base.Channel.ConsultarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prueba_1.LanderServices.ConsultarUsuarioResponse> ConsultarUsuarioAsync(string user, string Pass) {
            Prueba_1.LanderServices.ConsultarUsuarioRequest inValue = new Prueba_1.LanderServices.ConsultarUsuarioRequest();
            inValue.Body = new Prueba_1.LanderServices.ConsultarUsuarioRequestBody();
            inValue.Body.user = user;
            inValue.Body.Pass = Pass;
            return ((Prueba_1.LanderServices.User_WebServiceSoap)(this)).ConsultarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prueba_1.LanderServices.ParametrosOffice365Response Prueba_1.LanderServices.User_WebServiceSoap.ParametrosOffice365(Prueba_1.LanderServices.ParametrosOffice365Request request) {
            return base.Channel.ParametrosOffice365(request);
        }
        
        public Prueba_1.LanderServices.Office365 ParametrosOffice365() {
            Prueba_1.LanderServices.ParametrosOffice365Request inValue = new Prueba_1.LanderServices.ParametrosOffice365Request();
            inValue.Body = new Prueba_1.LanderServices.ParametrosOffice365RequestBody();
            Prueba_1.LanderServices.ParametrosOffice365Response retVal = ((Prueba_1.LanderServices.User_WebServiceSoap)(this)).ParametrosOffice365(inValue);
            return retVal.Body.ParametrosOffice365Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prueba_1.LanderServices.ParametrosOffice365Response> Prueba_1.LanderServices.User_WebServiceSoap.ParametrosOffice365Async(Prueba_1.LanderServices.ParametrosOffice365Request request) {
            return base.Channel.ParametrosOffice365Async(request);
        }
        
        public System.Threading.Tasks.Task<Prueba_1.LanderServices.ParametrosOffice365Response> ParametrosOffice365Async() {
            Prueba_1.LanderServices.ParametrosOffice365Request inValue = new Prueba_1.LanderServices.ParametrosOffice365Request();
            inValue.Body = new Prueba_1.LanderServices.ParametrosOffice365RequestBody();
            return ((Prueba_1.LanderServices.User_WebServiceSoap)(this)).ParametrosOffice365Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prueba_1.LanderServices.ListarUsuariosResponse Prueba_1.LanderServices.User_WebServiceSoap.ListarUsuarios(Prueba_1.LanderServices.ListarUsuariosRequest request) {
            return base.Channel.ListarUsuarios(request);
        }
        
        public Prueba_1.LanderServices.UsuariosAplic[] ListarUsuarios(string User_Cliente_WebService, string Key_Cliente_WebService) {
            Prueba_1.LanderServices.ListarUsuariosRequest inValue = new Prueba_1.LanderServices.ListarUsuariosRequest();
            inValue.Body = new Prueba_1.LanderServices.ListarUsuariosRequestBody();
            inValue.Body.User_Cliente_WebService = User_Cliente_WebService;
            inValue.Body.Key_Cliente_WebService = Key_Cliente_WebService;
            Prueba_1.LanderServices.ListarUsuariosResponse retVal = ((Prueba_1.LanderServices.User_WebServiceSoap)(this)).ListarUsuarios(inValue);
            return retVal.Body.ListarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prueba_1.LanderServices.ListarUsuariosResponse> Prueba_1.LanderServices.User_WebServiceSoap.ListarUsuariosAsync(Prueba_1.LanderServices.ListarUsuariosRequest request) {
            return base.Channel.ListarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prueba_1.LanderServices.ListarUsuariosResponse> ListarUsuariosAsync(string User_Cliente_WebService, string Key_Cliente_WebService) {
            Prueba_1.LanderServices.ListarUsuariosRequest inValue = new Prueba_1.LanderServices.ListarUsuariosRequest();
            inValue.Body = new Prueba_1.LanderServices.ListarUsuariosRequestBody();
            inValue.Body.User_Cliente_WebService = User_Cliente_WebService;
            inValue.Body.Key_Cliente_WebService = Key_Cliente_WebService;
            return ((Prueba_1.LanderServices.User_WebServiceSoap)(this)).ListarUsuariosAsync(inValue);
        }
    }
}
